<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<EditorConfigFiles Remove="D:\Courses - Online\CSharp\Web Development\AspNetCore Mvc\Asp.Net Core 6 Fundamentals - Gil Cleeren\BethanysPieShop.App\BethanysPieShop.SharedConfiguration\.editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<None Include="D:\Courses - Online\CSharp\Web Development\AspNetCore Mvc\Asp.Net Core 6 Fundamentals - Gil Cleeren\BethanysPieShop.App\BethanysPieShop.SharedConfiguration\.editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BethanysPieShopAdvanced.BusinessLogic\BethanysPieShop.BusinessLogic.csproj" />
	  <ProjectReference Include="..\BethanysPieShopAdvanced.DataAccess\BethanysPieShop.DataAccess.csproj" />
	</ItemGroup>

</Project>
