global using AutoMapper;
global using BethanysPieShop.Common.Constant;
global using BethanysPieShop.Common.Dto;
global using BethanysPieShop.Common.Entity;
global using BethanysPieShop.Common.EnumType;
global using BethanysPieShop.Common.Interface;
global using BethanysPieShop.Common.Pagination;
global using BethanysPieShop.Common.Utility;
global using Microsoft.EntityFrameworkCore;
